### ISSUE TITLE
ReferenceError: IS_HTTPS is not defined

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/nodelab#9]
When running the server locally on my machine

```npm start```

I get the following error:

```shell
> nodelab@0.0.1 start /Users/michaelpalumbo/nodelab
> node server.js

/Users/michaelpalumbo/nodelab/server.js:36
if (IS_HTTPS) {
^

ReferenceError: IS_HTTPS is not defined
    at Object.<anonymous> (/Users/michaelpalumbo/nodelab/server.js:36:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodelab@0.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodelab@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michaelpalumbo/.npm/_logs/2021-11-23T21_06_08_518Z-debug.log
```

**Comment by DMGregory** [comment]
@michaelpalumbo I see `IS_HTTPS` defined on line 29: `const IS_HTTPS = !IS_DEBUG && !IS_HEROKU;` - is that not present in your version?

**Comment by michaelpalumbo** [comment]
Hey @DMGregory sorry I thought I replied to this already. Closing this in favour of issue #8
